#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-gateway-relay
chmod 750 /etc/chirpstack-gateway-relay
chmod 640 /etc/chirpstack-gateway-relay/*.toml

#DEBHELPER#
