#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-gateway-mesh
chmod 750 /etc/chirpstack-gateway-mesh
chmod 640 /etc/chirpstack-gateway-mesh/*.toml

#DEBHELPER#
