
# Logging settings.
[logging]

  # Log level.
  #
  # Valid options are:
  #   * TRACE
  #   * DEBUG
  #   * INFO
  #   * WARN
  #   * ERROR
  #   * OFF
  level="INFO"

  # Log to syslog.
  #
  # When set to true, log messages are being written to syslog instead of stdout.
  log_to_syslog=false


# Relay configuration.
[relay]

  # Border Gateway.
  #
  # If this is set to true, then the ChirpStack Gateway Relay will consider
  # this gateway as a Border Gateway, meaning that it will unwrap relayed
  # uplinks and forward these to the proxy API, rather than relaying these.
  border_gateway=false

  # Relay frequencies.
  #
  # The ChirpStack Gateway Relay will randomly use one of the configured
  # frequencies when relaying uplink and downlink messages.
  frequencies=[
    868100000,
    868300000,
    868500000,
  ]

  # TX Power (EIRP).
  #
  # The TX Power in EIRP used when relaying uplink and downlink messages.
  tx_power=16

  # Data-rate properties.
  #
  # The data-rate properties when relaying uplink and downlink messages.
  [relay.data_rate]
  
    # Modulation.
    #
    # Valid options are: LORA, FSK
    modulation="LORA"

    # Spreading-factor (LoRa).
    spreading_factor=7

    # Bandwidth (LoRa).
    bandwidth=125000

    # Code-rate (LoRa).
    code_rate="4/5"

    # Bitrate (FSK).
    bitrate=0


  # Proxy API configuration.
  #
  # If the Gateway Relay is configured to operate as Border Gateway. It
  # will unwrap relayed uplink frames, and will wrap downlink payloads that
  # must be relayed. In this case the ChirpStack MQTT Forwarder must be
  # configured to use the proxy API instead of the Concentratord API.
  #
  # Payloads of devices that are under the direct coverage of this gateway
  # are transparently proxied between the ChirpStack MQTT Forwarder and
  # ChirpStack Concentratord.
  #
  # This configuration is only used when the border_gateway option is set
  # to true.
  [relay.proxy_api]

    # Event PUB socket bind.
    event_bind="ipc:///tmp/gateway_relay_event"

    # Command REP socket bind.
    command_bind="ipc:///tmp/gateway_relay_command"


# Backend configuration.
[backend]

  # ChirpStack Concentratord configuration (Relay <> End Device).
  [backend.concentratord]

    # Event API URL.
    event_url="ipc:///tmp/concentratord_event"

    # Command API URL.
    command_url="ipc:///tmp/concentratord_command"


  # ChirpStack Concentratord configuration (Relay <> Relay).
  #
  # While not required, this configuration makes it possible to use a different
  # Concentratord instance for the Relay <> Relay communication. E.g. this
  # makes it possible to use ISM2400 for Relay <> Relay communication.
  [backend.relay_concentratord]

    # Event API URL.
    event_url="ipc:///tmp/concentratord_event"

    # Command API URL.
    command_url="ipc:///tmp/concentratord_command"

